# Occupation

### Introduction:

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

### Step 3. Assign it to a variable called users.

In [3]:
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user", sep = '|')

In [4]:
users.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

### Step 4. Discover what is the mean age per occupation

In [6]:
users.groupby('occupation')['age'].mean()

occupation
administrator    38.746835
artist           31.392857
doctor           43.571429
educator         42.010526
engineer         36.388060
entertainment    29.222222
executive        38.718750
healthcare       41.562500
homemaker        32.571429
lawyer           36.750000
librarian        40.000000
marketing        37.615385
none             26.555556
other            34.523810
programmer       33.121212
retired          63.071429
salesman         35.666667
scientist        35.548387
student          22.081633
technician       33.148148
writer           36.311111
Name: age, dtype: float64

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [19]:
gender_occupation_counts = users.groupby('occupation')['gender'].value_counts(normalize=True)
gender_occupation_counts.xs('M', level='gender').sort_values(ascending=False)

occupation
doctor           1.000000
engineer         0.970149
technician       0.962963
retired          0.928571
programmer       0.909091
executive        0.906250
scientist        0.903226
entertainment    0.888889
lawyer           0.833333
salesman         0.750000
educator         0.726316
student          0.693878
other            0.657143
marketing        0.615385
writer           0.577778
none             0.555556
administrator    0.544304
artist           0.535714
librarian        0.431373
healthcare       0.312500
homemaker        0.142857
Name: proportion, dtype: float64

### Step 6. For each occupation, calculate the minimum and maximum ages

In [23]:
users.groupby('occupation')['age'].describe()[['min', 'max']]

                min   max
occupation
administrator  21.0  70.0
artist         19.0  48.0
doctor         28.0  64.0
educator       23.0  63.0
engineer       22.0  70.0
entertainment  15.0  50.0
executive      22.0  69.0
healthcare     22.0  62.0
homemaker      20.0  50.0
lawyer         21.0  53.0
librarian      23.0  69.0
marketing      24.0  55.0
none           11.0  55.0
other          13.0  64.0
programmer     20.0  63.0
retired        51.0  73.0
salesman       18.0  66.0
scientist      23.0  55.0
student         7.0  42.0
technician     21.0  55.0
writer         18.0  60.0

### Step 7. For each combination of occupation and gender, calculate the mean age

In [30]:
round(users.groupby(['occupation', 'gender'])['age'].mean())

occupation     gender
administrator  F         41.0
               M         37.0
artist         F         30.0
               M         32.0
doctor         M         44.0
educator       F         39.0
               M         43.0
engineer       F         30.0
               M         37.0
entertainment  F         31.0
               M         29.0
executive      F         44.0
               M         38.0
healthcare     F         40.0
               M         45.0
homemaker      F         34.0
               M         23.0
lawyer         F         40.0
               M         36.0
librarian      F         40.0
               M         40.0
marketing      F         37.0
               M         38.0
none           F         36.0
               M         19.0
other          F         35.0
               M         34.0
programmer     F         32.0
               M         33.0
retired        F         70.0
               M         63.0
salesman       F         27.0
               M         39.0
scientist      F         28.0
               M         36.0
student        F         21.0
               M         23.0
technician     F         38.0
               M         33.0
writer         F         38.0
               M         35.0
Name: age, dtype: float64

### Step 8.  For each occupation present the percentage of women and men

In [33]:
round((users.groupby('occupation')['gender'].value_counts(normalize=True))*100)

occupation     gender
administrator  M          54.0
               F          46.0
artist         M          54.0
               F          46.0
doctor         M         100.0
educator       M          73.0
               F          27.0
engineer       M          97.0
               F           3.0
entertainment  M          89.0
               F          11.0
executive      M          91.0
               F           9.0
healthcare     F          69.0
               M          31.0
homemaker      F          86.0
               M          14.0
lawyer         M          83.0
               F          17.0
librarian      F          57.0
               M          43.0
marketing      M          62.0
               F          38.0
none           M          56.0
               F          44.0
other          M          66.0
               F          34.0
programmer     M          91.0
               F           9.0
retired        M          93.0
               F           7.0
salesman       M          75.0
               F          25.0
scientist      M          90.0
               F          10.0
student        M          69.0
               F          31.0
technician     M          96.0
               F           4.0
writer         M          58.0
               F          42.0
Name: proportion, dtype: float64