# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [ ]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [ ]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data)

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [ ]:
url = 'https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data'
data = pd.read_csv(url, sep = r"\s+")

In [ ]:
data

,Yr,Mo,Dy,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
0,61,1,1,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1,61,1,2,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
2,61,1,3,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
3,61,1,4,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
4,61,1,5,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6569,78,12,27,17.58,16.96,17.62,8.08,13.21,11.67,14.46,15.59,14.04,14.00,17.21,40.08
6570,78,12,28,13.21,5.46,13.46,5.00,8.12,9.42,14.33,16.25,15.25,18.05,21.79,41.46
6571,78,12,29,14.00,10.29,14.42,8.71,9.71,10.54,19.17,12.46,14.50,16.42,18.88,29.58
6572,78,12,30,18.50,14.04,21.29,9.13,12.75,9.71,18.08,12.87,12.46,12.12,14.67,28.79
6573,78,12,31,20.33,17.41,27.29,9.59,12.08,10.13,19.25,11.63,11.58,11.38,12.08,22.08

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [ ]:
data["Yr"] = data["Yr"] + 1900
date_series = (
    data["Yr"].astype(str)
    + "-"
    + data["Mo"].astype(str).str.zfill(2)
    + "-"
    + data["Dy"].astype(str).str.zfill(2)
)

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [ ]:
data["Dates"] = pd.to_datetime(date_series, format="%Y-%m-%d")
data = data.drop(columns=["Yr", 'Mo', 'Dy']).set_index("Dates")

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [ ]:
data.isna().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

### Step 7. Compute how many non-missing values there are in total.

In [ ]:
data.notnull().sum().sum()

np.int64(78857)

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [ ]:
data.mean().mean()

np.float64(10.227982360836938)

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days

#### A different set of numbers for each location.

In [ ]:
data.describe()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
count,6568.000000,6571.000000,6572.000000,6569.000000,6572.000000,6574.000000,6571.000000,6572.000000,6571.000000,6573.000000,6574.000000,6570.000000
mean,12.362987,10.644314,11.660526,6.306468,10.455834,7.092254,9.797343,8.495053,8.493590,8.707332,13.121007,15.599079
std,5.618413,5.267356,5.008450,3.605811,4.936125,3.968683,4.977555,4.499449,4.166872,4.503954,5.835037,6.699794
min,0.670000,0.210000,1.500000,0.000000,0.130000,0.000000,0.000000,0.000000,0.000000,0.040000,0.130000,0.670000
25%,8.120000,6.670000,8.000000,3.580000,6.750000,4.000000,6.000000,5.090000,5.370000,5.330000,8.710000,10.710000
50%,11.710000,10.170000,10.920000,5.750000,9.960000,6.830000,9.210000,8.080000,8.170000,8.290000,12.500000,15.000000
75%,15.920000,14.040000,14.670000,8.420000,13.540000,9.670000,12.960000,11.420000,11.190000,11.630000,16.880000,19.830000
max,35.800000,33.370000,33.840000,28.460000,37.540000,26.160000,30.370000,31.080000,25.880000,28.210000,42.380000,42.540000

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [ ]:
day_stats = pd.DataFrame()
day_stats['Min'] = data.min(axis=1)
day_stats['Max'] = data.max(axis=1)
day_stats['Mean'] = data.mean(axis=1)
day_stats['Std'] = data.std(axis=1)

In [ ]:
day_stats

             Min    Max       Mean       Std
Dates
1961-01-01  9.29  18.50  13.018182  2.808875
1961-01-02  6.50  17.54  11.336364  3.188994
1961-01-03  6.17  18.50  11.641818  3.681912
1961-01-04  1.79  11.75   6.619167  3.198126
1961-01-05  6.17  13.33  10.630000  2.445356
...          ...    ...        ...       ...
1978-12-27  8.08  40.08  16.708333  7.868076
1978-12-28  5.00  41.46  15.150000  9.687857
1978-12-29  8.71  29.58  14.890000  5.756836
1978-12-30  9.13  28.79  15.367500  5.540437
1978-12-31  9.59  27.29  15.402500  5.702483

[6574 rows x 4 columns]

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [ ]:
data.loc[data.index.month == 1].mean()

RPT    14.847325
VAL    12.914560
ROS    13.299624
KIL     7.199498
SHA    11.667734
BIR     8.054839
DUB    11.819355
CLA     9.512047
MUL     9.543208
CLO    10.053566
BEL    14.550520
MAL    18.028763
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

In [66]:
data.groupby(data.index.to_period("Y")).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Dates,,,,,,,,,,,,
1961,12.299583,10.351796,11.362369,6.958227,10.881763,7.729726,9.733923,8.858788,8.647652,9.835577,13.502795,13.680773
1962,12.246923,10.110438,11.732712,6.960440,10.657918,7.393068,11.020712,8.793753,8.316822,9.676247,12.930685,14.323956
1963,12.813452,10.836986,12.541151,7.330055,11.724110,8.434712,11.075699,10.336548,8.903589,10.224438,13.638877,14.999014
1964,12.363661,10.920164,12.104372,6.787787,11.454481,7.570874,10.259153,9.467350,7.789016,10.207951,13.740546,14.910301
1965,12.451370,11.075534,11.848767,6.858466,11.024795,7.478110,10.618712,8.879918,7.907425,9.918082,12.964247,15.591644
1966,13.461973,11.557205,12.020630,7.345726,11.805041,7.793671,10.579808,8.835096,8.514438,9.768959,14.265836,16.307260
1967,12.737151,10.990986,11.739397,7.143425,11.630740,7.368164,10.652027,9.325616,8.645014,9.547425,14.774548,17.135945
1968,11.835628,10.468197,11.409754,6.477678,10.760765,6.067322,8.859180,8.255519,7.224945,7.832978,12.808634,15.017486
1969,11.166356,9.723699,10.902000,5.767973,9.873918,6.189973,8.564493,7.711397,7.924521,7.754384,12.621233,15.762904
1970,12.600329,10.726932,11.730247,6.217178,10.567370,7.609452,9.609890,8.334630,9.297616,8.289808,13.183644,16.456027
1971,11.273123,9.095178,11.088329,5.241507,9.440329,6.097151,8.385890,6.757315,7.915370,7.229753,12.208932,15.025233
1972,12.463962,10.561311,12.058333,5.929699,9.430410,6.358825,9.704508,7.680792,8.357295,7.515273,12.727377,15.028716
1973,11.828466,10.680493,10.680493,5.547863,9.640877,6.548740,8.482110,7.614274,8.245534,7.812411,12.169699,15.441096
1974,13.643096,11.811781,12.336356,6.427041,11.110986,6.809781,10.084603,9.896986,9.331753,8.736356,13.252959,16.947671
1975,12.008575,10.293836,11.564712,5.269096,9.190082,5.668521,8.562603,7.843836,8.797945,7.382822,12.631671,15.307863
1976,11.737842,10.203115,10.761230,5.109426,8.846339,6.311038,9.149126,7.146202,8.883716,7.883087,12.332377,15.471448
1977,13.099616,11.144493,12.627836,6.073945,10.003836,8.586438,11.523205,8.378384,9.098192,8.821616,13.459068,16.590849
1978,12.504356,11.044274,11.380000,6.082356,10.167233,7.650658,9.489342,8.800466,9.089753,8.301699,12.967397,16.771370

### Step 13. Downsample the record to a monthly frequency for each location.

In [67]:
data.groupby(data.index.to_period("M")).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Dates,,,,,,,,,,,,
1961-01,14.841333,11.988333,13.431613,7.736774,11.072759,8.588065,11.184839,9.245333,9.085806,10.107419,13.880968,14.703226
1961-02,16.269286,14.975357,14.441481,9.230741,13.852143,10.937500,11.890714,11.846071,11.821429,12.714286,18.583214,15.411786
1961-03,10.890000,11.296452,10.752903,7.284000,10.509355,8.866774,9.644194,9.829677,10.294138,11.251935,16.410968,15.720000
1961-04,10.722667,9.427667,9.998000,5.830667,8.435000,6.495000,6.925333,7.094667,7.342333,7.237000,11.147333,10.278333
1961-05,9.860968,8.850000,10.818065,5.905333,9.490323,6.574839,7.604000,8.177097,8.039355,8.499355,11.900323,12.011613
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-08,9.645161,8.259355,9.032258,4.502903,7.368065,5.935161,5.650323,5.417742,7.241290,5.536774,10.466774,12.054194
1978-09,10.913667,10.895000,10.635000,5.725000,10.372000,9.278333,10.790333,9.583000,10.069333,8.939000,15.680333,19.391333
1978-10,9.897742,8.670968,9.295806,4.721290,8.525161,6.774194,8.115484,7.337742,8.297742,8.243871,13.776774,17.150000
1978-11,16.151667,14.802667,13.508000,7.317333,11.475000,8.743000,11.492333,9.657333,10.701333,10.676000,17.404667,20.723000
1978-12,16.175484,13.748065,15.635161,7.094839,11.398710,9.241613,12.077419,10.194839,10.616774,11.028710,13.859677,21.371613

### Step 14. Downsample the record to a weekly frequency for each location.

In [68]:
data.groupby(data.index.to_period("W")).mean()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Dates,,,,,,,,,,,,
1960-12-26/1961-01-01,15.040000,14.960000,13.170000,9.290000,NaN,9.870000,13.670000,10.250000,10.830000,12.580000,18.500000,15.040000
1961-01-02/1961-01-08,13.541429,11.486667,10.487143,6.417143,9.474286,6.435714,11.061429,6.616667,8.434286,8.497143,12.481429,13.238571
1961-01-09/1961-01-15,12.468571,8.967143,11.958571,4.630000,7.351429,5.072857,7.535714,6.820000,5.712857,7.571429,11.125714,11.024286
1961-01-16/1961-01-22,13.204286,9.862857,12.982857,6.328571,8.966667,7.417143,9.257143,7.875714,7.145714,8.124286,9.821429,11.434286
1961-01-23/1961-01-29,19.880000,16.141429,18.225714,12.720000,17.432857,14.828571,15.528571,15.160000,14.480000,15.640000,20.930000,22.530000
...,...,...,...,...,...,...,...,...,...,...,...,...
1978-11-27/1978-12-03,14.934286,11.232857,13.941429,5.565714,10.215714,8.618571,9.642857,7.685714,9.011429,9.547143,11.835714,18.728571
1978-12-04/1978-12-10,20.740000,19.190000,17.034286,9.777143,15.287143,12.774286,14.437143,12.488571,13.870000,14.082857,18.517143,23.061429
1978-12-11/1978-12-17,16.758571,14.692857,14.987143,6.917143,11.397143,7.272857,10.208571,7.967143,9.168571,8.565714,11.102857,15.562857
1978-12-18/1978-12-24,11.155714,8.008571,13.172857,4.004286,7.825714,6.290000,7.798571,8.667143,7.151429,8.072857,11.845714,18.977143
1978-12-25/1978-12-31,14.951429,11.801429,16.035714,6.507143,9.660000,8.620000,13.708571,10.477143,10.868571,11.471429,12.947143,26.844286

### Step 15. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [72]:
weekly = data.resample('W').agg(['min', 'max', 'std'])
weekly.iloc[1:53]

              RPT                     VAL                     ROS         \
              min    max       std    min    max       std    min    max
Dates
1961-01-08  10.58  18.50  2.631321   6.63  16.88  3.949525   7.62  12.33
1961-01-15   9.04  19.75  3.555392   3.54  12.08  3.148945   7.08  19.50
1961-01-22   4.92  19.83  5.337402   3.42  14.37  3.837785   7.29  20.79
1961-01-29  13.62  25.04  4.619061   9.96  23.91  5.170224  12.67  25.84
1961-02-05  10.58  24.21  5.251408   9.46  24.21  5.187395   9.04  19.70
1961-02-12  16.00  24.54  3.587677  11.54  21.42  3.608373  13.67  21.34
1961-02-19   6.04  22.50  5.064609  11.63  20.17  3.575012   6.13  19.41
1961-02-26   7.79  25.80  7.020716   7.08  21.50  5.147348   6.08  22.42
1961-03-05  10.96  13.33  0.997721   8.83  17.00  2.851955   8.17  13.67
1961-03-12   4.88  14.79  3.732263   8.08  16.96  3.230167   7.54  16.38
1961-03-19   4.92  16.88  3.860036   9.46  15.54  2.352867   5.25  13.96
1961-03-26   6.29  15.00  3.613298   2.58  11.63  3.657265   4.79  15.63
1961-04-02   5.88  18.25  5.046922   3.50  16.29  4.687315   5.09  14.96
1961-04-09   4.50  18.12  4.604392   7.04  14.62  2.845399   9.29  18.29
1961-04-16   4.71  15.50  3.937727   4.83  12.25  2.607118   3.92  15.79
1961-04-23   4.00  21.09  5.676655   3.71  15.41  4.631736   3.33  17.00
1961-04-30   4.08  16.29  4.349662   6.50  14.46  2.871425   2.54  14.96
1961-05-07   9.87  23.00  5.025507  10.29  19.79  3.750835   8.42  21.21
1961-05-14   3.54  12.79  3.371022   3.96  15.12  3.782947   4.63  12.33
1961-05-21   4.88  15.04  3.631730   3.58  10.17  2.468906   5.91  15.96
1961-05-28   4.96  11.79  2.739433   3.67  12.50  3.378537   3.58  20.96
1961-06-04   7.00  15.92  3.099701   4.75   9.79  1.868125   6.83  15.96
1961-06-11   8.29  14.42  2.248597   6.83  11.54  1.524836   6.04  11.58
1961-06-18   6.13  14.33  3.009482   4.12  14.54  3.509444   6.50  15.50
1961-06-25   4.00   9.00  1.982035   3.25   9.50  2.212460   5.13  10.37
1961-07-02   7.21  13.13  2.557856   6.34  14.37  2.902411   7.62  10.79
1961-07-09   7.29  17.50  3.664855   3.75  10.75  2.686658   7.41  14.92
1961-07-16   8.63  22.50  5.168710   7.87  19.29  3.849630   8.00  14.29
1961-07-23   3.04   5.88  1.047978   2.92   6.79  1.400010   4.08  12.67
1961-07-30   6.13  16.08  4.157641   4.63  13.79  3.203206   6.42  15.67
1961-08-06   7.67  16.08  2.950887   5.09  15.79  3.985226   5.54  15.59
1961-08-13   2.88  14.21  4.422268   4.42  10.00  2.053326   6.00  11.63
1961-08-20  13.13  18.91  2.283635   7.25  13.62  2.523416   9.17  14.04
1961-08-27   7.67  18.16  3.395857   6.87  14.58  3.174702   9.50  17.83
1961-09-03   3.63  14.46  4.398615   1.13  22.00  7.474025   2.42  12.75
1961-09-10   5.00  17.62  5.207278   3.04  13.59  4.003996   3.63  14.88
1961-09-17   5.33  28.75  7.679190   7.12  22.08  5.360585   7.29  26.50
1961-09-24   6.92  10.25  1.267399   2.92  13.62  3.445262   5.33  12.17
1961-10-01  10.34  23.21  4.559572   6.96  13.62  2.812482   7.87  17.58
1961-10-08   3.13  16.08  5.596710   3.63  16.96  5.060803   4.96  17.83
1961-10-15   3.71  17.12  4.780675   6.13  13.25  2.707483   4.21  20.96
1961-10-22  10.46  28.62  7.888314   3.75  19.46  5.998199   9.92  22.63
1961-10-29   4.33  26.42  7.957637   2.75  21.25  6.879973   4.79  23.09
1961-11-05   5.88  15.79  3.369201   3.96  13.46  3.900278   6.54  14.33
1961-11-12   5.46  16.08  3.939811   5.50  10.75  2.141191   3.83  20.41
1961-11-19   7.50  15.00  2.784358   4.21  13.00  3.208548   6.46  32.71
1961-11-26   5.75  14.29  3.214368   3.29  11.79  3.277904   4.42  14.46
1961-12-03   7.92  23.75  5.704669   4.67  18.71  5.107089   8.00  19.92
1961-12-10  10.83  23.71  4.890152   9.21  21.37  4.115506   9.71  20.54
1961-12-17   9.29  21.34  4.095106   8.63  17.62  3.587886   9.04  19.00
1961-12-24  11.46  24.41  4.959717   9.79  16.13  2.220866   8.08  22.13
1961-12-31   5.04  20.54  5.787783   3.08  16.04  4.566479   2.13  29.33

                       KIL  ...       MUL    CLO                     BEL  \
                 std   min  ...       std    min    max       std    min
Dates                       ...
1961-01-08  1.604761  4.58  ...  1.722255   5.88  10.46  1.704941   5.46
1961-01-15  5.034959  0.67  ...  3.500975   2.67  14.58  4.084293   5.25
1961-01-22  5.086229  1.04  ...  4.169112   2.71  16.71  4.783952   6.50
1961-01-29  4.665843  6.04  ...  4.902057  11.04  19.95  3.713368  14.04
1961-02-05  3.975166  5.09  ...  2.802490   5.50  13.13  2.839501   9.17
1961-02-12  3.290303  8.38  ...  2.914760  12.25  17.79  1.746749  15.21
1961-02-19  4.196621  4.21  ...  2.560591   9.21  16.58  2.531361  14.09
1961-02-26  5.578470  2.21  ...  4.705163   7.00  20.04  4.920064   9.59
1961-03-05  1.796871  5.88  ...  2.610124   9.79  14.09  1.593685  11.58
1961-03-12  3.592909  3.13  ...  3.657690   5.09  15.79  3.655113  10.21
1961-03-19  2.939244  4.29  ...  3.301880   7.29  15.34  3.099472  11.29
1961-03-26  4.041121  4.42  ...  2.469432   8.33  14.50  2.538224   8.25
1961-04-02  3.678996  2.75  ...  4.025317   6.46  14.21  3.191115   7.21
1961-04-09  2.902991  3.21  ...  1.935058   3.67  10.50  2.336182   7.62
1961-04-16  4.585752  2.33  ...  2.123279   4.00   9.67  2.161137   5.75
1961-04-23  5.456290  1.58  ...  3.656682   3.83  14.37  3.347972   6.75
1961-04-30  3.732776  1.87  ...  2.718926   2.71  11.46  2.840568   5.13
1961-05-07  4.301778  6.46  ...  3.558856   8.63  17.54  3.620819   4.79
1961-05-14  3.002225  1.04  ...  5.126826   1.83  17.92  5.460237   6.54
1961-05-21  3.767505  3.63  ...  1.613885   4.17   9.29  2.216889   6.63
1961-05-28  6.355768  2.42  ...  1.990891   5.17  11.46  2.575661   6.13
1961-06-04  3.474607  3.42  ...  1.954609   5.91  12.04  2.096989   8.71
1961-06-11  1.887475  3.21  ...  1.695090   5.21  10.92  2.158323   5.37
1961-06-18  3.429057  2.92  ...  2.900464   3.08  14.71  3.792400   7.29
1961-06-25  1.916454  2.88  ...  2.042257   7.83  15.00  2.286218  11.00
1961-07-02  1.161629  4.42  ...  1.745125   7.96  12.38  1.564144   6.96
1961-07-09  2.995919  3.54  ...  3.453210   6.21  16.79  3.657179   7.08
1961-07-16  2.166206  5.58  ...  3.978635   4.25  14.92  3.271899   5.04
1961-07-23  2.783208  1.46  ...  0.873207   3.92   7.75  1.439785   4.21
1961-07-30  3.276465  2.83  ...  4.504844   4.92  15.75  4.350268   7.87
1961-08-06  3.483894  4.17  ...  3.217501   5.41  12.83  2.903018   6.17
1961-08-13  2.174407  2.50  ...  2.718228   5.25   9.92  2.073777   5.88
1961-08-20  1.766039  6.83  ...  2.339544   9.13  17.83  2.730237   9.59
1961-08-27  3.071403  3.96  ...  4.120185   7.46  15.96  3.855302   5.75
1961-09-03  4.395383  2.37  ...  4.155931   5.96  16.13  3.993736   4.79
1961-09-10  3.922643  2.75  ...  3.767708   1.75  11.71  3.649278   5.41
1961-09-17  6.638947  3.96  ...  4.847073   9.67  25.21  5.128338  13.92
1961-09-24  2.322229  2.62  ...  1.523142   2.83  10.71  2.354092   4.54
1961-10-01  4.201062  5.79  ...  1.790306   5.29  17.46  3.908397   7.79
1961-10-08  4.394234  1.46  ...  3.717239   2.42  12.21  4.296870   4.79
1961-10-15  5.979099  3.67  ...  2.947025   5.37  15.21  3.569308   8.54
1961-10-22  5.463782  6.83  ...  3.785875  11.08  26.38  5.890511  10.88
1961-10-29  7.428776  1.71  ...  4.448500   5.83  22.13  6.277629   8.50
1961-11-05  2.461109  3.79  ...  3.003274   7.67  15.79  2.784450  10.29
1961-11-12  6.779554  1.87  ...  2.153102   2.62  10.88  2.843518   6.13
1961-11-19  9.415716  1.50  ...  3.488521   1.25  14.04  4.402588   0.71
1961-11-26  3.622254  2.04  ...  2.392934   6.92  14.12  2.747452   6.50
1961-12-03  4.163650  3.29  ...  3.658796   3.63  13.00  3.680477   5.50
1961-12-10  4.682044  3.83  ...  3.452864   5.75  15.50  4.156207  10.71
1961-12-17  3.843380  4.46  ...  4.333020   4.67  17.41  4.633398   5.50
1961-12-24  5.653229  0.58  ...  4.243508   2.46  15.34  4.637096   5.29
1961-12-31  9.739918  0.42  ...  3.325214   1.96  10.83  3.526625   3.75

                               MAL
              max       std    min    max       std
Dates
1961-01-08  17.54  4.349139  10.88  16.46  1.773062
1961-01-15  20.71  5.552215   5.17  16.92  4.692355
1961-01-22  15.92  3.626584   6.79  17.96  4.237239
1961-01-29  27.71  5.210726  17.50  27.63  3.874721
1961-02-05  19.33  4.210858   7.17  19.25  4.336104
1961-02-12  26.38  4.063753  17.04  21.84  1.828705
1961-02-19  29.63  5.910938  10.96  22.58  4.685377
1961-02-26  23.21  5.091162   6.67  23.87  6.182283
1961-03-05  23.45  4.332331   8.83  17.54  3.021387
1961-03-12  22.71  4.358759   5.54  22.54  5.769890
1961-03-19  22.79  3.779727  11.34  22.95  4.331958
1961-03-26  21.34  4.318069  13.13  22.50  3.701846
1961-04-02  18.63  4.179854   7.17  19.58  3.924555
1961-04-09  17.16  3.147781   7.21  15.34  2.598271
1961-04-16  16.17  3.641464   5.66  12.87  2.747842
1961-04-23  19.21  4.735096   4.96  20.46  5.908542
1961-04-30  13.04  2.948237   2.67  17.50  5.108365
1961-05-07  28.08  8.003490   3.83  26.58  7.728504
1961-05-14  18.66  3.968272   3.33  26.30  7.858246
1961-05-21  12.00  1.975853   5.91  14.96  3.310819
1961-05-28  14.33  3.024524   8.00  17.04  3.811818
1961-06-04  17.00  2.611139  10.63  17.96  2.593586
1961-06-11  16.17  3.993062   5.96  19.83  4.925055
1961-06-18  25.25  6.477887   6.13  24.71  6.242673
1961-06-25  19.08  2.498386  13.75  21.50  3.063011
1961-07-02  21.87  6.303747   8.50  16.79  3.652313
1961-07-09  20.41  4.537988  12.08  21.29  3.665705
1961-07-16  20.25  4.971060   5.96  21.96  4.974273
1961-07-23  10.13  2.050218   5.41  10.92  2.133994
1961-07-30  22.17  5.580903   6.13  25.37  6.664574
1961-08-06  18.54  4.901377   9.08  20.25  4.448251
1961-08-13  14.29  2.931302   5.88  15.16  3.356585
1961-08-20  21.92  4.086725  13.04  24.30  3.934238
1961-08-27  23.38  6.711322   8.29  22.29  4.947608
1961-09-03  24.71  7.678051   5.41  22.54  6.308087
1961-09-10  15.83  4.220584   3.37  20.25  6.049619
1961-09-17  23.91  4.464252  14.67  33.09  6.332885
1961-09-24  20.96  5.235868   5.25  14.62  3.113507
1961-10-01  21.37  5.091268   4.04  17.16  4.696504
1961-10-08  17.83  4.800403   4.83  19.62  5.462002
1961-10-15  20.46  4.113200  10.75  21.04  4.098130
1961-10-22  24.71  5.645871  13.46  33.45  7.468377
1961-10-29  27.29  7.056150   9.83  30.88  8.340881
1961-11-05  20.17  4.038493  13.37  23.58  3.870800
1961-11-12  12.58  2.532196   5.71  15.54  3.690752
1961-11-19   9.59  3.643285   2.00  13.25  3.787654
1961-11-26  20.46  5.407223   4.25  22.58  6.475867
1961-12-03  19.04  5.552648   5.88  21.29  5.233192
1961-12-10  21.79  4.667933   7.58  29.33  7.345893
1961-12-17  22.83  6.531043   6.50  21.12  5.665006
1961-12-24  17.67  5.065308   2.62  16.62  5.048035
1961-12-31  13.21  3.262217   6.63  15.21  3.012729

[52 rows x 36 columns]