# MPG Cars

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [2]:
import numpy as np
import pandas as pd

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a variable called cars1 and cars2

In [4]:
cars1 = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv")
cars2 = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv")

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [10]:
cars1 = cars1.loc[:, 'mpg':'car']

In [11]:
cars1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
193,24.0,6,200,81,3012,17.6,76,1,ford maverick
194,22.5,6,232,90,3085,17.6,76,1,amc hornet
195,29.0,4,85,52,2035,22.2,76,1,chevrolet chevette
196,24.5,4,98,60,2164,22.1,76,1,chevrolet woody
197,29.0,4,90,70,1937,14.2,76,2,vw rabbit

### Step 5. What is the number of observations in each dataset?

In [17]:
cars1.shape

(198, 9)

In [18]:
cars2.shape

(200, 9)

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [21]:
cars = pd.concat([cars1, cars2])
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
196,44.0,4,97,52,2130,24.6,82,2,vw pickup
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage
198,28.0,4,120,79,2625,18.6,82,1,ford ranger
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [23]:
abc = np.random.randint(15000, 73000, 398)
abc

array([72268, 61266, 66280, 18925, 20882, 33817, 51437, 51551, 17093,
       50466, 33544, 47532, 15878, 32940, 33402, 47972, 24805, 65055,
       41336, 54120, 56150, 65807, 41389, 60953, 38653, 27881, 26621,
       65697, 22903, 36383, 22609, 43791, 45988, 69117, 41429, 27171,
       33246, 24337, 32745, 67952, 49363, 17886, 22866, 34330, 56844,
       29206, 18963, 42564, 62275, 44486, 72817, 29736, 54644, 45102,
       20637, 16044, 40638, 21636, 61000, 52309, 49161, 19739, 67229,
       53817, 27160, 58763, 62016, 16813, 60693, 32142, 24081, 66248,
       66447, 24287, 64362, 27630, 19919, 52122, 47578, 45931, 24458,
       33261, 48376, 21501, 36170, 21076, 50302, 32538, 33761, 42610,
       42417, 40526, 23502, 24794, 59155, 51435, 65051, 70357, 56542,
       51966, 34444, 63427, 54321, 46547, 42435, 27225, 40923, 55681,
       16553, 67436, 72634, 53666, 19017, 21483, 16468, 49502, 65813,
       42847, 47532, 25256, 63113, 26763, 47474, 62482, 40730, 48741,
       59364, 41954, 62795, 30743, 53994, 51757, 68167, 44796, 67517,
       51334, 57804, 67697, 37240, 29728, 17902, 66330, 64154, 67768,
       60095, 45867, 20697, 35703, 53262, 64200, 72388, 45839, 50452,
       54840, 64610, 59295, 37391, 39943, 38658, 50686, 31921, 25595,
       67049, 45067, 59629, 32862, 46105, 42108, 21957, 34637, 53622,
       65403, 70557, 70412, 72228, 71737, 59129, 27679, 47332, 68640,
       48758, 47481, 67886, 69474, 19127, 24738, 44277, 72797, 52477,
       47620, 25768, 20393, 68777, 15938, 36376, 36733, 51603, 62259,
       38990, 23829, 27707, 63226, 43643, 29590, 71985, 20675, 15890,
       45496, 44325, 41905, 43295, 39943, 44677, 72279, 47112, 42631,
       31743, 16105, 63484, 48875, 61717, 38575, 53318, 61685, 67665,
       53117, 42384, 26275, 27262, 58246, 21279, 51224, 42655, 35463,
       53911, 69864, 68072, 61971, 70947, 50926, 36408, 66406, 20011,
       53389, 69686, 68384, 66628, 20182, 17785, 69877, 54894, 64386,
       69251, 60373, 42059, 64309, 18301, 46388, 16706, 18864, 43938,
       39720, 16260, 36380, 32828, 71047, 56105, 50026, 49190, 39300,
       68361, 66973, 69104, 59339, 28678, 29179, 26760, 54744, 69309,
       59881, 40093, 17204, 31445, 53785, 23744, 52521, 35402, 18145,
       29494, 28301, 36111, 47519, 51172, 19952, 64680, 34611, 40763,
       28298, 32017, 21015, 21214, 50881, 65032, 52625, 57856, 55869,
       35571, 15488, 55816, 68119, 48543, 44917, 59971, 58919, 67474,
       25503, 65710, 37036, 60309, 35515, 58722, 49411, 26641, 56517,
       69281, 47334, 55872, 34838, 47340, 24182, 19484, 46625, 37887,
       17729, 62218, 65825, 28828, 15456, 22771, 22670, 44812, 67486,
       55395, 67716, 38557, 25047, 38121, 72981, 52266, 39508, 54214,
       34314, 64300, 71226, 23120, 51735, 27529, 57134, 34958, 41869,
       57288, 50320, 53516, 52802, 37998, 42801, 55006, 24089, 46125,
       42482, 70266, 35378, 22328, 27715, 22696, 70833, 24548, 32009,
       17710, 52382, 56160, 36504, 25291, 66019, 72664, 58355, 41614,
       70450, 21519, 29724, 27491, 38466, 25574, 25705, 22902, 66694,
       24276, 20353])

### Step 8. Add the column owners to cars

In [24]:
cars['owwner'] = abc

In [26]:
cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owwner
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,72268
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,61266
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,66280
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,18925
4,17.0,8,302,140,3449,10.5,70,1,ford torino,20882