# US - Baby Names

### Introduction:

We are going to use a subset of [US Baby Names](https://www.kaggle.com/kaggle/us-baby-names) from Kaggle.  
In the file it will be names from 2004 until 2014


### Step 1. Import the necessary libraries

In [1]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv).

### Step 3. Assign it to a variable called baby_names.

In [2]:
baby_names = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/US_Baby_Names/US_Baby_Names_right.csv")

### Step 4. See the first 10 entries

In [4]:
baby_names.head(10)

   Unnamed: 0     Id      Name  Year Gender State  Count
0       11349  11350      Emma  2004      F    AK     62
1       11350  11351   Madison  2004      F    AK     48
2       11351  11352    Hannah  2004      F    AK     46
3       11352  11353     Grace  2004      F    AK     44
4       11353  11354     Emily  2004      F    AK     41
5       11354  11355   Abigail  2004      F    AK     37
6       11355  11356    Olivia  2004      F    AK     33
7       11356  11357  Isabella  2004      F    AK     30
8       11357  11358    Alyssa  2004      F    AK     29
9       11358  11359    Sophia  2004      F    AK     28

### Step 5. Delete the column 'Unnamed: 0' and 'Id'

In [10]:
baby_names = baby_names.iloc[:, 2:]

In [11]:
baby_names

            Name  Year Gender State  Count
0           Emma  2004      F    AK     62
1        Madison  2004      F    AK     48
2         Hannah  2004      F    AK     46
3          Grace  2004      F    AK     44
4          Emily  2004      F    AK     41
...          ...   ...    ...   ...    ...
1016390     Seth  2014      M    WY      5
1016391  Spencer  2014      M    WY      5
1016392     Tyce  2014      M    WY      5
1016393   Victor  2014      M    WY      5
1016394   Waylon  2014      M    WY      5

[1016395 rows x 5 columns]

### Step 6. What year has the highest number of baby names in the dataset?

In [23]:
baby_names.groupby('Year')['Count'].sum().sort_values(ascending=False)

Year
2007    3412417
2006    3387737
2008    3340318
2005    3305315
2004    3293984
2009    3232116
2010    3116548
2014    3113611
2011    3079145
2012    3073858
2013    3066443
Name: Count, dtype: int64

### Step 7. Is there more male or female names in the dataset?

In [34]:
baby_names['Gender'].value_counts()

Gender
F    558846
M    457549
Name: count, dtype: int64

### Step 8. Group the dataset by name and assign to names

In [26]:
names = baby_names.groupby('Name')

In [30]:
names['Count'].sum()

Name
Aaban        12
Aadan        23
Aadarsh       5
Aaden      3426
Aadhav        6
           ...
Zyra         42
Zyrah        11
Zyren         6
Zyria        59
Zyriah       58
Name: Count, Length: 17632, dtype: int64

### Step 9. How many different names exist in the dataset?

In [33]:
names['Count'].sum().shape

(17632,)

### Step 10. What is the name with most occurrences?

In [37]:
names['Count'].sum().sort_values(ascending=False)

Name
Jacob       242874
Emma        214852
Michael     214405
Ethan       209277
Isabella    204798
             ...
Abigaile         5
Shatha           5
Zykeriah         5
Zunaira          5
Ezel             5
Name: Count, Length: 17632, dtype: int64

### Step 11. How many different names have the least occurrences?

In [49]:
names['Count'].sum()[names['Count'].sum() == names['Count'].sum().sort_values().iloc[0]]

Name
Aadarsh     5
Aadin       5
Aaima       5
Aalaya      5
Aaminah     5
           ..
Zyien       5
Zyire       5
Zykeriah    5
Zykierra    5
Zymari      5
Name: Count, Length: 2578, dtype: int64

### Step 12. What is the median name occurrence?

In [57]:
names['Count'].sum()[names['Count'].sum() == names['Count'].sum().median()]

Name
Aishani    49
Alara      49
Alysse     49
Ameir      49
Anely      49
           ..
Sriram     49
Trinton    49
Vita       49
Yoni       49
Zuleima    49
Name: Count, Length: 66, dtype: int64

### Step 13. What is the standard deviation of names?

In [58]:
names['Count'].sum().std()

11006.069467891111

### Step 14. Get a summary with the mean, min, max, std and quartiles.

In [59]:
names['Count'].sum().describe()

count     17632.000000
mean       2008.932169
std       11006.069468
min           5.000000
25%          11.000000
50%          49.000000
75%         337.000000
max      242874.000000
Name: Count, dtype: float64